import type { StudySource } from '@/lib/memory/scoring'

/** Inclusive [floor, ceiling] on the 1-5 severity scale. */
export type SeverityBand = readonly [number, number]
export type BandTable = Record<string, SeverityBand>

/**
 * MC/TF distractors are generated by corrupting a named KLP with a named
 * corruption, so a wrong pick is by construction a FULL instance of that
 * corruption. They carry maximum magnitude and resolve to their ceiling.
 */
export const MC_TF_MAGNITUDE = 10

/**
 * Fallback for a type with no band — an unknown string that survived
 * validation. Neutral rather than harsh: a fabricated severity is worse than
 * a conservative one.
 */
const FALLBACK_BAND: SeverityBand = [1, 3]

/**
 * Default bands. The five accuracy CEILINGS are pinned, not chosen: MC/TF
 * resolve to the ceiling, so they must equal `CORRUPTION_SEVERITY` for the
 * band model to be a no-op on the existing path. tests/errors/bands.test.ts
 * asserts this, so drift is a build failure.
 *
 * The FLOORS are the new freedom, and are where magnitude sensitivity lands:
 * a soft inversion no longer scores like a true one.
 */
export const DEFAULT_BANDS: BandTable = {
  // accuracy — first five have pinned ceilings
  conflation: [3, 5],
  inversion: [2, 5],
  misapplication: [2, 4],
  overgeneralization: [1, 3],
  factual_error: [1, 2],
  omission: [2, 5],
  incomplete: [1, 3],
  unsupported_leap: [2, 4],
  fabrication: [3, 5],

  // clarity
  incoherent_syntax: [2, 5],
  disorganized: [2, 4],
  no_thesis: [1, 3],
  ambiguous_referent: [1, 3],
  undefined_jargon: [1, 3],
  hedging: [1, 3],

  // conciseness — kitchen_sink's floor sits above rambling's ceiling so it
  // always outranks it; rambling overlaps redundancy so a severe ramble can
  // beat a mild one. too_terse spans the full range because how bad
  // under-answering is depends on subject command — resolved in articulation.ts.
  kitchen_sink: [4, 5],
  too_terse: [1, 5],
  rambling: [2, 3],
  over_qualification: [1, 3],
  padding: [1, 2],
  redundancy: [1, 2],
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value))
}

/**
 * Compose a type's band with an instance magnitude into a 1-5 severity.
 *
 * Severity stays 1-5 so `computeSignificance`'s arithmetic is unchanged: with
 * relevance and severity both 1-5, `0.55r + 0.45s` scaled by 2 still lands in
 * 2-10 before dimension weight.
 *
 * The true/false dock is applied AFTER band resolution and is unchanged from
 * `severityFromCorruption`: selecting one of four named alternatives says more
 * about a learner's model than flipping a single bit. It is not a guess-rate
 * adjustment — guess rate discounts CORRECT answers.
 */
export function resolveSeverity(input: {
  type: string
  /** 1-10. `MC_TF_MAGNITUDE` for a generated distractor. */
  magnitude: number
  mode: StudySource
  bands?: BandTable
}): number {
  const table = input.bands ?? DEFAULT_BANDS
  const [floor, ceiling] = table[input.type] ?? FALLBACK_BAND
  const magnitude = clamp(input.magnitude, 1, 10)

  const interpolated = floor + (ceiling - floor) * ((magnitude - 1) / 9)
  const docked = input.mode === 'quiz-tf' ? interpolated - 1 : interpolated

  return clamp(Math.round(docked), 1, 5)
}
